src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategoryRepository::class)
 */
class Category
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Public;

    /**
     * @ORM\OneToMany(targetEntity=FlashCard::class, mappedBy="category", orphanRemoval=true)
     */
    private $ListCards;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="categories")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    public function __construct()
    {
        $this->ListCards = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function isPublic(): ?bool
    {
        return $this->Public;
    }

    public function setPublic(bool $Public): self
    {
        $this->Public = $Public;

        return $this;
    }

    /**
     * @return Collection<int, FlashCard>
     */
    public function getListCards(): Collection
    {
        return $this->ListCards;
    }

    public function addListCard(FlashCard $listCard): self
    {
        if (!$this->ListCards->contains($listCard)) {
            $this->ListCards[] = $listCard;
            $listCard->setCategory($this);
        }

        return $this;
    }

    public function removeListCard(FlashCard $listCard): self
    {
        if ($this->ListCards->removeElement($listCard)) {
            // set the owning side to null (unless already changed)
            if ($listCard->getCategory() === $this) {
                $listCard->setCategory(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

src/Controller/EntrainementController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Repository\CategoryRepository;
use App\Repository\FlashCardRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

class EntrainementController extends AbstractController
{
    /** Entrainement global
     * @Route("/entrainement", name="app_entrainement")
     */
    public function index(CategoryRepository $categoryRepository): Response
    {
        $categories = $categoryRepository->getFullTrain();
        return $this->render('entrainement/index.html.twig', [
            'categories' => $categories,
        ]);
    }

    /** Entrainement toutes les catégories d'une personne
     * @Route("/entrainementComplet", name="app_user_entrainement")
     */
    public function userTrainingFull(): Response
    {
        $cards = [];
        foreach ($this->getUser()->getCategories() as $category)
        {
            foreach ($category->getListCards() as $card)
            {
                array_push($cards,$card);
            }
        }

        return $this->render('entrainement/fullUser.html.twig', [
            'cards' => $cards,
        ]);
    }

    /** Entrainement d'une catégorie spécifique
     * @Route("/entrainement/{id}", name="app_entrainement_category")
     */
    public function entrainementCategory(int $id, CategoryRepository $categoryRepository, FlashCardRepository $flashCardRepository): Response
    {
        $this->getUser();
        $category = $categoryRepository->find($id);
        $cards = $flashCardRepository->findCardByCategory($category);
        if (!$category->isPublic() && $category->getUser() !== $this->getUser()) {
            return $this->redirectToRoute('app_home');
        } else {
            return $this->render('entrainement/trainingCategory.html.twig', [
                'cards' => $cards
            ]);
        }
    }

    /** Entrainement d'une catégorie spécifique
     * @Route("/successCard/{id}", name="app_card_success")
     */
    public function cardSuccess(int $id, FlashCardRepository $flashCardRepository, EntityManagerInterface $entityManager, UserInterface $user): Response
    {
        $flashCard = $flashCardRepository->find($id);
        if ($flashCard->getCategory()->getUser() === $user) {
            $flashCard->setSuccess(true);
            $flashCard->setSuccessfull($flashCard->getSuccessfull() + 1);
            $entityManager->flush();
            return $this->json(['code' => 200, 'message' => 'Bien joué']);
        } elseif ($flashCard->getCategory()->isPublic()) {
            return $this->json(['code' => 200, 'message' => 'Bien joué']);
        }
        return $this->json(['code' => 403, 'message' => 'Problème au niveau de la carte : ' . $flashCard->getId()], 403);
    }

    /** Entrainement d'une catégorie spécifique
     * @Route("/errorCard/{id}", name="app_card_error")
     */
    public function cardError(int $id, FlashCardRepository $flashCardRepository, EntityManagerInterface $entityManager, UserInterface $user): Response
    {
        $flashCard = $flashCardRepository->find($id);
        if ($flashCard->getCategory()->getUser() === $user) {
            $flashCard->setSuccess(false);
            $flashCard->setError($flashCard->getError() + 1);
            $entityManager->flush();
            return $this->json(['code' => 200, 'message' => 'Dommage']);
        } elseif ($flashCard->getCategory()->isPublic()) {
            return $this->json(['code' => 200, 'message' => 'Dommage']);
        }
        return $this->json(['code' => 403, 'message' => 'Problème au niveau de la carte : ' . $flashCard->getId()], 403);
    }
}

templates/entrainement/fullUser.html.twig
{% extends 'base.html.twig' %}

{% block title %}Entrainement complet{% endblock %}

{% block stylesheets %}
  <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/login.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/training.css') }}">
  <style>
      .card__face--front {
          padding-top: 1rem;
          background: linear-gradient(#141e30, #243b55);
      }
      .card-body {
          margin-top: 3rem;
      }
  </style>
{% endblock %}

{% block body %}

  <div class="container text-center center-block mt-3">
    {% for card in cards %}
      <div class="{{ card.id }}{% if loop.index != 1 %} d-none{% endif %}">
        <div class="row">
          <div class="col-12 text-center">
          </div>
        </div>
        <div class="scene scene--card ">
          <div class="card">

            <div class="card__face card__face--front">
              <div class="card-title fw-bold">{{ card.category.titre }}</div>
              <div class="card-body">{{ card.front }}</div>
            </div>
            <div class="card__face card__face--back">{{ card.back }}</div>
          </div>
        </div>
        <div>
          <a href="{{ path('app_card_success', {'id': card.id}) }}" class="btn btn-success" data-id="{{ card.id }}">
            Réussi
          </a>
          <a href="{{ path('app_card_error', {'id': card.id}) }}" class="btn btn-danger" data-id="{{ card.id }}">
            Échoué
          </a>
        </div>
      </div>
    {% endfor %}
    <div class="end-round d-none">

    </div>
  </div>
{% endblock %}
{% block javascripts %}
  {{ parent() }}
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <script>
      const values = [];
      {% for card in cards %}
      values.push({{ card.id }})
      {% endfor %}
  </script>
  <script>
      var cards = document.querySelectorAll('.card');

      [...cards].forEach((card) => {
          card.addEventListener('click', function () {
              card.classList.toggle('is-flipped');
          });
      });

      function successCard(event) {
          event.preventDefault();
          let id = this.dataset.id;
          let url = this.href;
          let card = this.parentElement.parentElement;
          axios.get(url).then(function (response) {
              if (response.data.code === 200) {
                {% set cards = cards|slice(1, cards|length) %}
                  tata.success('Carte', response.data.message, {
                      position: 'tm'
                  });
              } else {
                  tata.error('Carte', 'La carte est bien passé', {
                      position: 'tm'
                  });
              }
              card.classList.add("d-none");
              values.shift();
              document.getElementsByClassName(values[0])[0].classList.remove('d-none');
          }).catch(function (error) {
              if (error.response.status === 403) {
                  tata.error('Problème', error.response.data.message, {
                      position: 'tm'
                  });
              } else {
                  tata.error('Problème', 'Une erreur c\'est produit', {
                      position: 'tm'
                  });
              }
          })
      }

      function errorCard(event) {
          event.preventDefault();
          let id = this.dataset.id;
          let url = this.href;
          let card = this.parentElement.parentElement;
          axios.get(url).then(function (response) {
              if (response.data.code === 200) {
                {% set cards = cards|slice(1, cards|length) %}
                {% set cards = cards|merge([cards.0]) %}
                  tata.error('Carte', response.data.message, {
                      position: 'tm'
                  });
              } else {
                  tata.error('Carte', 'La carte est bien passé', {
                      position: 'tm'
                  });
              }
              card.classList.add("d-none");
              values.shift()
              values.push(id)
              document.getElementsByClassName(values[0])[0].classList.remove('d-none');
              document.querySelectorAll('.is-flipped').forEach((element) => {
                  element.classList.remove('is-flipped')
              });
          }).catch(function (error) {
              if (error.response.status === 403) {
                  tata.error('Problème', error.response.data.message, {
                      position: 'tm'
                  });
              } else {
                  tata.error('Problème', 'Une erreur c\'est produit', {
                      position: 'tm'
                  });
              }
          })
      }

      document.querySelectorAll('a.btn-success').forEach(function (link) {
          link.addEventListener('click', successCard);
      })
      document.querySelectorAll('a.btn-danger').forEach(function (link) {
          link.addEventListener('click', errorCard);
      })

  </script>
{% endblock %}

templates/entrainement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des flash cartes{% endblock %}

{% block stylesheets %}
  <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/login.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/gestion.css') }}">
{% endblock %}
{% block body %}
  <div class="container mt-3">
    <div class="row">
      <div class="col-12 text-center center-block mb-3">
        <a href="#" class="btn btn-training-full">Entrainement full</a>
      </div>
      {% for category in categories %}
        <div class="col-3 pl-2 pr-2 mb-3 card-container">
          <div class="card">
            <div class="card-header ">
              <div class="row">
                <div class="col-3">
                  <span class="badge badge-info">{% if category.public == 0 %}Privé{% else %}Public{% endif %}</span>
                </div>
                <div class="col-6 text-center title">
                  {{ category.titre }}
                </div>
                <div class="col-3">
                </div>
              </div>
            </div>
            <div class="card-body center-block text-center">
              <div class="row">
                <a href="{{ path('app_entrainement_category', {'id': category.id}) }}" class="btn btn-success">S'entrainer</a>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

{% block javascripts %}
  {{ parent() }}
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <script>
      function onClickDelete(event) {
          event.preventDefault();
          const url = this.href;
          const card = this.parentElement.parentElement.parentElement.parentElement
          axios.get(url).then(function (response) {
              if (response.data.code === 200) {
                  tata.success(response.data.message, '');
                  card.classList.add("d-none")

              } else {
                  tata.error(response.data.message, '');
              }
          }).catch(function (error) {
              if (error.response.status === 403) {
                  tata.error(error.response.data.message, '');
              } else {
                  tata.error('Une erreur c\'est produit', '');
              }
          })
      }

      document.querySelectorAll('a.btn-danger').forEach(function (link) {
          link.addEventListener('click', onClickDelete);
      })
  </script>
{% endblock %}

templates/entrainement/trainingCategory.html.twig
{% extends 'base.html.twig' %}

{% block title %}Entrainement {{ cards.0.category.titre }}{% endblock %}
{% block stylesheets %}
  <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/login.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/training.css') }}">
{% endblock %}

{% block body %}

  <div class="container text-center center-block mt-3">
    {% for card in cards %}
      <div class="{{ card.id }}{% if loop.index != 1 %} d-none{% endif %}">
        <div class="scene scene--card" id="{{ card.id }}" style="{% if card.type == 1 %}width: 300px;{% endif %}">
          <div class="card">
            <div class="card__face card__face--front">
              {% if card.type == 1 %}
                {{ card.front }}
              {% else %}
                <img class="fit-picture"
                     src="{{ card.front }}">
              {% endif %}
            </div>
            <div class="card__face card__face--back">
              {{ card.back }}
            </div>
          </div>
        </div>
        <div>
          <a href="{{ path('app_card_success', {'id': card.id}) }}" class="btn btn-success" data-id="{{ card.id }}">
            Réussi
          </a>
          <a href="{{ path('app_card_error', {'id': card.id}) }}" class="btn btn-danger" data-id="{{ card.id }}">
            Échoué
          </a>
        </div>
      </div>
    {% endfor %}
    <div class="end-round d-none pt-5">
      <div class="col-12 text-center center-block mb-3">
        <a href="{{ path('app_entrainement_category', {id: cards.0.category.id}) }}" class="btn btn-end-training mr-5">Se réentrainer</a>
        <a href="{{ path('app_entrainement') }}" class="btn btn-training-full ml-5">Retour au catégories</a>
      </div>
    </div>
  </div>
{% endblock %}
{% block javascripts %}
  {{ parent() }}
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <script>
      const values = [];
      {% for card in cards %}
      {% if card.type == 2 %}
      getMeta(
          "{{ card.front }}",
          (width, height) => {
              document.getElementById('{{ card.id }}').style.width = width / height * 260 + 'px';
          }
      );
      {% endif %}
      values.push({{ card.id }})
      {% endfor %}

      function getMeta(url, callback) {
          const img = new Image();
          img.src = url;
          img.onload = function () {
              callback(this.width, this.height);
          }
      }
  </script>
  <script>
      var cards = document.querySelectorAll('.card');

      [...cards].forEach((card) => {
          card.addEventListener('click', function () {
              card.classList.toggle('is-flipped');
          });
      });

      function successCard(event) {
          event.preventDefault();
          let id = this.dataset.id;
          let url = this.href;
          let card = this.parentElement.parentElement;
          axios.get(url).then(function (response) {
              if (response.data.code === 200) {
                {% set cards = cards|slice(1, cards|length) %}
                  tata.success('Carte', response.data.message, {
                      position: 'tm'
                  });
              } else {
                  tata.error('Carte', 'La carte est bien passé', {
                      position: 'tm'
                  });
              }
              card.classList.add("d-none");
              values.shift();
              if (values.length === 0) {
                  document.getElementsByClassName('end-round')[0].classList.remove('d-none');
              }
              document.getElementsByClassName(values[0])[0].classList.remove('d-none');
          }).catch(function (error) {
              if (error.response.status === 403) {
                  tata.error('Problème', error.response.data.message, {
                      position: 'tm'
                  });
              } else {
                  tata.error('Problème', 'Une erreur c\'est produit', {
                      position: 'tm'
                  });
              }
          })
      }

      function errorCard(event) {
          event.preventDefault();
          let id = this.dataset.id;
          let url = this.href;
          let card = this.parentElement.parentElement;
          axios.get(url).then(function (response) {
              if (response.data.code === 200) {
                {% set cards = cards|slice(1, cards|length) %}
                {% set cards = cards|merge([cards]|first) %}
                  tata.error('Carte', response.data.message, {
                      position: 'tm'
                  });
              } else {
                  tata.error('Carte', 'La carte est bien passé', {
                      position: 'tm'
                  });
              }
              card.classList.add("d-none");
              values.shift()
              values.push(id)
              document.getElementsByClassName(values[0])[0].classList.remove('d-none');
              document.querySelectorAll('.is-flipped').forEach((element) => {
                  element.classList.remove('is-flipped')
              });
          }).catch(function (error) {
              if (error.response.status === 403) {
                  tata.error('Problème', error.response.data.message, {
                      position: 'tm'
                  });
              } else {
                  tata.error('Problème', 'Une erreur c\'est produit', {
                      position: 'tm'
                  });
              }
          })
      }

      document.querySelectorAll('a.btn-success').forEach(function (link) {
          link.addEventListener('click', successCard);
      })
      document.querySelectorAll('a.btn-danger').forEach(function (link) {
          link.addEventListener('click', errorCard);
      })

  </script>
{% endblock %}